set(_CATKIN_CURRENT_PACKAGE "quad")
set(quad_MAINTAINER "aranya <aranya@todo.todo>")
set(quad_DEPRECATED "")
set(quad_VERSION "0.0.0")
set(quad_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "cv_bridge" "image_transport")
set(quad_RUN_DEPENDS "image_transport" "cv_bridge" "sensor_msgs" "roscpp" "rospy" "std_msgs")
set(quad_BUILDTOOL_DEPENDS "catkin")